"""Market-data access for the course.

Two rules shape this package:

1. **Offline first.** Every loader reads a small, committed sample by default.
   Tests never touch the network, so the repo stays green on any machine.
2. **Nothing licensed is redistributed.** The committed samples are
   *synthetic* — generated by `make_samples.py` from a fixed seed with
   realistic shape (NSE bhavcopy columns, yfinance OHLCV columns, EDGAR-style
   filing sections) and fictional issuers. Live fetchers exist for NSE,
   yfinance and SEC EDGAR, but they are opt-in (``FORGE_ALLOW_NETWORK=1``) and
   they cache to a gitignored directory.
"""

from common.data.loaders import (  # noqa: F401
    SAMPLE_SYMBOLS,
    fetch_bhavcopy_live,
    fetch_edgar_filing_live,
    fetch_ohlcv_live,
    load_bhavcopy,
    load_filings,
    load_ohlcv,
    load_orders,
)

__all__ = [
    "load_bhavcopy",
    "load_ohlcv",
    "load_filings",
    "load_orders",
    "fetch_ohlcv_live",
    "fetch_bhavcopy_live",
    "fetch_edgar_filing_live",
    "SAMPLE_SYMBOLS",
]
