/**
 * t30-e3 composition.
 *
 * Scenes (component + props) live in `script.md`; durations come from
 * `timings.json`, regenerated by `video/kokoro/narrate.py`. This file only
 * names the composition, so a re-worded script never needs a code change.
 */

import type { Timings } from "../../src/Episode";
import type { EpisodeSpec } from "../../src/register";
import timings from "./timings.json";

export const T30_E3_EPISODES: EpisodeSpec[] = [
  { id: "t30-e3", timings: timings as unknown as Timings, captions: true },
];
